### ISSUE TITLE
TypeError: Cannot read property 'selectedPath' of undefined

### ISSUE THREAD

**Issue by singularitti** [aviatesk/atom-open-in-app#14]
When I am trying to open anything from tree-view, it complains that "TypeError: Cannot read property 'selectedPath' of undefined". No console output.
![screenshot](https://user-images.githubusercontent.com/25192197/63914683-f672af80-ca01-11e9-996a-ac03b2a12777.png)
Atom version: 1.40.1
OS: macOS 10.14.6
plugin version: 0.2.0

**Comment by aviatesk** [comment]
Can't reproduce this.
Are you sure your tree-view package is active ?

**Comment by singularitti** [comment]
Well, now it is working. Thank you!
